#!/usr/bin/env python3
"""Generate the UI's built-in assets as C++ headers.

  pip install pillow numpy
  python3 tools/gen_assets.py

Inputs:  assets/goblin_logo.png, assets/fonts/*.ttf (SIL OFL, see assets/fonts/*-OFL.txt)
Outputs: src/ui/assets/GoblinArt.h, src/ui/assets/Fonts.h  (committed; re-run after editing inputs)
"""
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/ui/assets"


def rgb565(r, g, b):
    return ((int(r) & 0xF8) << 8) | ((int(g) & 0xFC) << 3) | (int(b) >> 3)


def c_array(name, ctype, values, per_line=16, fmt="{}"):
    lines = []
    vals = list(values)
    for i in range(0, len(vals), per_line):
        lines.append("  " + ", ".join(fmt.format(v) for v in vals[i:i + per_line]) + ",")
    return f"const {ctype} {name}[{len(vals)}] = {{\n" + "\n".join(lines) + "\n};\n"


# ---------------------------------------------------------------------------- goblin
def key_background(im):
    """Flood-fill the flat dark-grey background from the borders."""
    h, w, _ = im.shape
    bg = np.zeros((h, w), bool)
    q = deque([(y, x) for x in range(w) for y in (0, h - 1)] + [(y, x) for y in range(h) for x in (0, w - 1)])

    def is_bg(p):
        mx, mn = int(p.max()), int(p.min())
        return mx - mn < 10 and 15 <= mx <= 45

    while q:
        y, x = q.popleft()
        if bg[y, x] or not is_bg(im[y, x]):
            continue
        bg[y, x] = True
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            yy, xx = y + dy, x + dx
            if 0 <= yy < h and 0 <= xx < w and not bg[yy, xx]:
                q.append((yy, xx))
    return bg


def classify(rgb, alpha, eye_box=None, screen_box=None):
    """0 = other, 1 = skin (green, tintable), 2 = eye, 3 = device screen."""
    r, g, b = (rgb[..., i].astype(int) for i in range(3))
    mx, mn = rgb.max(-1).astype(int), rgb.min(-1).astype(int)
    h, w = alpha.shape
    yy, xx = np.mgrid[0:h, 0:w]
    cls = np.zeros((h, w), np.uint8)
    cls[(g > r + 8) & (g > b + 8) & (alpha > 0)] = 1
    if eye_box:
        x0, y0, x1, y1 = eye_box
        cls[(xx >= x0) & (xx <= x1) & (yy >= y0) & (yy <= y1) & (r > 130) & (r - g > 30) & (b < 120)] = 2
    if screen_box:
        x0, y0, x1, y1 = screen_box
        cls[(xx >= x0) & (xx <= x1) & (yy >= y0) & (yy <= y1) & (mx - mn > 40) & ((b > 90) | (g > 140))
            & ~((r > g) & (r > b))] = 3
    cls[alpha == 0] = 0
    return cls


def bbox_of(mask):
    ys, xs = np.where(mask)
    return int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())


def emit_sprite(prefix, rgba, cls):
    h, w = rgba.shape[:2]
    px = [rgb565(*rgba[y, x, :3]) for y in range(h) for x in range(w)]
    out = f"const uint16_t {prefix}W = {w};\nconst uint16_t {prefix}H = {h};\n"
    out += c_array(f"{prefix}Px", "uint16_t", px, 12, "0x{:04X}")
    out += c_array(f"{prefix}Alpha", "uint8_t", rgba[..., 3].flatten(), 24)
    out += c_array(f"{prefix}Class", "uint8_t", cls.flatten(), 32)
    return out


def gen_goblin():
    src = np.array(Image.open(ROOT / "assets/goblin_logo.png").convert("RGB"))
    bg = key_background(src)
    x0, y0, x1, y1 = bbox_of(~bg)
    x0, y0, x1, y1 = max(0, x0 - 1), max(0, y0 - 1), min(src.shape[1] - 1, x1 + 1), min(src.shape[0] - 1, y1 + 1)
    rgb = src[y0:y1 + 1, x0:x1 + 1]
    alpha = np.where(bg[y0:y1 + 1, x0:x1 + 1], 0, 255).astype(np.uint8)
    # Logo coordinates of the eyes and the device screen, shifted into the crop.
    eye_box = (44 - x0, 40 - y0, 80 - x0, 55 - y0)
    screen_box = (98 - x0, 44 - y0, 114 - x0, 70 - y0)
    cls = classify(rgb, alpha, eye_box, screen_box)
    rgba = np.dstack([rgb, alpha])

    h, w = alpha.shape
    mid = w // 2
    eyes = cls == 2
    lx0, ly0, lx1, ly1 = bbox_of(eyes & (np.mgrid[0:h, 0:w][1] < mid))
    rx0, ry0, rx1, ry1 = bbox_of(eyes & (np.mgrid[0:h, 0:w][1] >= mid))
    sy, sx = np.where(cls == 3)

    # Glow aura: dilated, blurred silhouette with an 8 px margin.
    pad = 8
    sil = Image.fromarray(np.pad(alpha, pad))
    aura = np.array(sil.filter(ImageFilter.MaxFilter(7)).filter(ImageFilter.GaussianBlur(4)))

    # Half-size goblin (encounter scene, badges): premultiplied-alpha downscale.
    small_h = 60
    small_w = round(w * small_h / h)
    small = np.array(Image.fromarray(rgba, "RGBA").resize((small_w, small_h), Image.LANCZOS))
    small_cls = classify(small[..., :3], small[..., 3])

    out = ["// Generated by tools/gen_assets.py from assets/goblin_logo.png. Do not edit.",
           "#pragma once", "#include <stdint.h>", "", "namespace art {", ""]
    out.append("// Pixel classes: 0 other, 1 skin (tintable), 2 eye, 3 device screen")
    out.append(emit_sprite("kGoblin", rgba, cls))
    out.append(f"const int16_t kGoblinEyeL[4] = {{{lx0}, {ly0}, {lx1}, {ly1}}};  // x0,y0,x1,y1")
    out.append(f"const int16_t kGoblinEyeR[4] = {{{rx0}, {ry0}, {rx1}, {ry1}}};")
    out.append(f"const int16_t kGoblinScreenX = {int(sx.mean())};\nconst int16_t kGoblinScreenY = {int(sy.mean())};")
    out.append(f"const uint16_t kGoblinAuraPad = {pad};")
    out.append(f"const uint16_t kGoblinAuraW = {aura.shape[1]};\nconst uint16_t kGoblinAuraH = {aura.shape[0]};")
    out.append(c_array("kGoblinAura", "uint8_t", aura.flatten(), 24))
    out.append(emit_sprite("kGoblinSmall", small, small_cls))
    out.append("}  // namespace art\n")
    (OUT / "GoblinArt.h").write_text("\n".join(out))
    print(f"goblin {w}x{h}, small {small_w}x{small_h}, aura {aura.shape[1]}x{aura.shape[0]}")


# ---------------------------------------------------------------------------- fonts
FONTS = [
    # name, file, px size, variation weight (None for static fonts)
    ("Small", "Rajdhani-SemiBold.ttf", 14, None),
    ("Body", "Rajdhani-Bold.ttf", 17, None),
    ("Title", "Orbitron-Variable.ttf", 13, 800),
    ("Big", "Orbitron-Variable.ttf", 22, 900),
    ("Huge", "Orbitron-Variable.ttf", 40, 900),
]


def gen_fonts():
    out = ["// Generated by tools/gen_assets.py from assets/fonts (SIL Open Font License). Do not edit.",
           "#pragma once", '#include "../gfx/Font.h"', "", "namespace fonts {", ""]
    total = 0
    for name, file, size, weight in FONTS:
        font = ImageFont.truetype(str(ROOT / "assets/fonts" / file), size)
        if weight:
            font.set_variation_by_axes([weight])
        ascent, descent = font.getmetrics()
        glyphs, bits = [], bytearray()
        pad = size
        for code in range(32, 127):
            ch = chr(code)
            img = Image.new("L", (size * 3, size * 3), 0)
            ImageDraw.Draw(img).text((pad, pad), ch, font=font, fill=255)
            adv = int(round(font.getlength(ch)))
            box = img.getbbox()
            if not box:
                glyphs.append((len(bits), 0, 0, 0, 0, adv))
                continue
            g = np.array(img.crop(box)) >> 4  # 4-bit coverage
            h, w = g.shape
            flat = g.flatten().tolist() + ([0] if (w * h) % 2 else [])
            off = len(bits)
            for i in range(0, len(flat), 2):
                bits.append((flat[i] << 4) | flat[i + 1])
            glyphs.append((off, w, h, box[0] - pad, box[1] - pad, adv))
        out.append(c_array(f"k{name}Bits", "uint8_t", bits, 24))
        out.append(f"const gfx::Glyph k{name}Glyphs[{len(glyphs)}] = {{")
        for gl in glyphs:
            out.append("  {%d, %d, %d, %d, %d, %d}," % gl)
        out.append("};")
        out.append(f"const gfx::Font k{name} = {{k{name}Bits, k{name}Glyphs, 32, 126, {ascent + descent}, {ascent}}};\n")
        total += len(bits) + len(glyphs) * 8
        print(f"font {name}: {file} {size}px, {len(bits)} bytes")
    out.append("}  // namespace fonts\n")
    (OUT / "Fonts.h").write_text("\n".join(out))
    print(f"fonts total ~{total // 1024} KB")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    gen_goblin()
    gen_fonts()
