#!/usr/bin/env python3
"""Write the trophy and hat lists the website shows (network-goblin-labs scout/data.js) from the
firmware source, so the profile pages use the same names as the device.
    python3 tools/web_data.py > ../network-goblin-labs/scout/data.js"""
import json, os, re

ROOT = os.path.join(os.path.dirname(__file__), "..")
src = open(os.path.join(ROOT, "src/core/Achievements.cpp")).read()
ach = []
pat = re.compile(r'(?:A\(|\{)"([a-z0-9_]+)",\s*"((?:[^"\\]|\\.)*)",\s*"((?:[^"\\]|\\.)*)",\s*k(\w+),\s*(?:Icon::)?\w+,\s*(true|false)')
for m in pat.finditer(src):
    ach.append({"id": m[1], "name": m[2], "desc": m[3], "tier": m[4].lower(), "secret": m[5] == "true"})

hsrc = open(os.path.join(ROOT, "src/core/Hats.cpp")).read()
hats = [{"name": m[1], "how": m[2]} for m in re.finditer(r'H\("([^"]+)",\s*"([^"]+)"', hsrc)]

print("// Generated by tools/web_data.py in the Network-Goblin-Scout repo. Don't edit by hand.")
print("export const ACHIEVEMENTS = " + json.dumps(ach, indent=0) + ";")
print("// Hat id = index + 1 (bit index in the synced 'hats' mask).")
print("export const HATS = " + json.dumps(hats, indent=0) + ";")
